### PR TITLE
adding latex support via katex

### PR DESCRIPTION
**Pull request by satra**

### CODE REVIEW

**Comment by jbpoline** [comment]
thanks - that's awesome

**Comment by yarikoptic** [comment]
Indeed it is! Nice job Satra! Fwiw Works even on the phone

**Comment by satra** [comment]
let's thank the person who provided the solution: https://github.com/cben/sandbox

**Comment by jbpoline** [comment]
Actually : I raised an issue on this. I may be doing something wrong but cannot see why the kramdown I'm putting in doesn't display properly.

**Pull request merged**
