### PR TITLE
WiP (do not merge): Changes from original neurohackweek to provide ReproNim branding

### PR DESCRIPTION
**Pull request by yarikoptic**
This PR is just to show what changes were made from the original neurohackweek template materials to quickly provide feedback etc. All changes appearing in this PR have been already pushed to gh-pages branch in this repository.

### CODE REVIEW

**Comment by satra** [comment]
can be seen here: http://www.reproducibleimaging.org/lesson-template/

**Comment by jbpoline** [comment]
Thanks - I was thinking of this and you were (of course) quicker :)

**Comment by yarikoptic** [comment]
ok -- I have stopped force-pushing to gh-pages, so now it should be safe to contribute directly or via PRs ;)
will submit few minor typo fixes upstream now

**Comment by jbpoline** [comment]
Quick naive question: this is only the gh-pages branch, I was half expecting something like:
- make html
- ghp-import -n $(BUILDDIR)/html/
- git push origin gh-pages:gh-pages --force

so, how does this work ?

**Comment by satra** [comment]
this page should guide you:

http://www.reproducibleimaging.org/lesson-template/01-first-part/

essentially you just have to add/update the markdown files, no making. if you want to make locally you'll need jekyll i believe.

**Comment by yarikoptic** [comment]
damn - again github either just rejects my replies via email or don't know what....  here is what I have replied a few minutes back:

>    so, how does this work ?
1. never do --force  unless it is needed and warranted ;)
2. no need for manual ghp-import -- just push and changes will be picked
   up.  But in general we should go through pull requests.  I just wanted
   to get the ball going quickly ;)  I will send one tiny PR now ;)
3. as for building locally:  haven't played much with jekyll yet so
   there might be "correct" way -- in my case

jekyll serve -w &  # to  start it serving off http://127.0.0.1:4000/

but because those are to be provided from /lesson-template of the
website,  after each regeneration I need to

ln -s .  _site/lesson-template

as a workaround.

**Comment by jbpoline** [comment]
thanks - working fine for me except....  $$ X = Y $$ doesnt show anything .. is it that related to : 

http://stackoverflow.com/questions/38945990/how-to-write-blogs-that-include-latex-math-in-github-pages-using-r-markdown

**Pull request closed without merging**
